#!/usr/bin/env node
//finding characters of a movie

const request = require('request')
request.get('https://swapi-api.alx-tools.com/api/films/' + process.argv[2], (error, request, response) => {
  if (error) console.log(error);

  const info = response;

  console.log(info.characters);
});
